data preprocessing

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data={
    'Name':['Ram','Kamal','Ajay'],
    'Age':[26,None,32],
    'Salary':[5000,6000,None]
}
df=pd.DataFrame(data)
print("Original data")
print(df)

Original data
    Name   Age  Salary
0    Ram  26.0  5000.0
1  Kamal   NaN  6000.0
2   Ajay  32.0     NaN

In [3]:
# null findout|Fillna|Dropna
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [4]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

    Name   Age  Salary
0    Ram  26.0  5000.0
1  Kamal  29.0  6000.0
2   Ajay  32.0     NaN

In [5]:
df.dropna()

    Name   Age  Salary
0    Ram  26.0  5000.0
1  Kamal  29.0  6000.0

In [6]:
df

    Name   Age  Salary
0    Ram  26.0  5000.0
1  Kamal  29.0  6000.0
2   Ajay  32.0     NaN

Encode categorial values

In [7]:
# 1 label encoding  --> answer is in Yes or No||| 1 or 0
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
data={
    'Name':['Ram','Kamal','Ajay','Neetu','Kavi','Sapu'],
    'Age':[26,None,32,20,21,22],
    'Salary':[5000,6000,None,7000,8000,9000],
    'Gender':['male','male','male',None,'female','female']
}
df=pd.DataFrame(data)
print("Original data")
print(df)
# !pip install scikit-learn
# label encoder

Original data
    Name   Age  Salary  Gender
0    Ram  26.0  5000.0    male
1  Kamal   NaN  6000.0    male
2   Ajay  32.0     NaN    male
3  Neetu  20.0  7000.0     NaN
4   Kavi  21.0  8000.0  female
5   Sapu  22.0  9000.0  female

In [8]:
# encoding
from sklearn.preprocessing import LabelEncoder
import pandas as pd
 
data = {
    'Name':['Ram','Kamal','Ajay','Neetu','Kavi','Sapu'],
    'Age':[25,None,32,20,21,22],
    'Salary':[5000,6000,None,7000,8000,9000],
    'Gender':['male','male','male',None,'female','female']
}
df = pd.DataFrame(data)
print("original dataframe")
print(df)
# label encoder
le = LabelEncoder()
df_label = df.copy()
df_label['Gender'] = df['Gender'].fillna('unknown')
df_label['Gender_encoder'] = le.fit_transform(df_label['Gender'])

print("After label encoding:")
print(df_label)

original dataframe
    Name   Age  Salary  Gender
0    Ram  25.0  5000.0    male
1  Kamal   NaN  6000.0    male
2   Ajay  32.0     NaN    male
3  Neetu  20.0  7000.0     NaN
4   Kavi  21.0  8000.0  female
5   Sapu  22.0  9000.0  female
After label encoding:
    Name   Age  Salary   Gender  Gender_encoder
0    Ram  25.0  5000.0     male               1
1  Kamal   NaN  6000.0     male               1
2   Ajay  32.0     NaN     male               1
3  Neetu  20.0  7000.0  unknown               2
4   Kavi  21.0  8000.0   female               0
5   Sapu  22.0  9000.0   female               0

In [11]:

data={
    'colors':['red','blue','green','red','blue']
}
df=pd.DataFrame(data)
print("original data ")
print(df)

# one hot encoding 
encoded_df=pd.get_dummies(df,columns=['colors'])
print("after one hot encoding")
print(encoded_df)

original data
  colors
0    red
1   blue
2  green
3    red
4   blue
after one hot encoding
   colors_blue  colors_green  colors_red
0        False         False        True
1         True         False       False
2        False          True       False
3        False         False        True
4         True         False       False

In [ ]:
# 5 different combination