In [1]:
from sklearn.preprocessing import LabelEncoder 
import pandas as pd
import numpy as np

In [2]:
# handle missing values 
data={
    "color":['red','green','blue','orange','green','blue',np.nan]
}
df=pd.DataFrame(data)
df

    color
0     red
1   green
2    blue
3  orange
4   green
5    blue
6     NaN

In [3]:
df.isnull().sum()

color    1
dtype: int64

In [4]:
df.dropna(inplace=True)
df

    color
0     red
1   green
2    blue
3  orange
4   green
5    blue

In [5]:
# label encoding 
df
le=LabelEncoder()
df['color_encoder']=le.fit_transform(df['color'])
df

    color  color_encoder
0     red              3
1   green              1
2    blue              0
3  orange              2
4   green              1
5    blue              0

In [6]:
df['color_encoder1']=LabelEncoder().fit_transform(df['color'])
df

    color  color_encoder  color_encoder1
0     red              3               3
1   green              1               1
2    blue              0               0
3  orange              2               2
4   green              1               1
5    blue              0               0

In [7]:
import sklearn
df['color_encoder2']=sklearn.preprocessing.LabelEncoder().fit_transform(df['color'])
df

    color  color_encoder  color_encoder1  color_encoder2
0     red              3               3               3
1   green              1               1               1
2    blue              0               0               0
3  orange              2               2               2
4   green              1               1               1
5    blue              0               0               0

In [8]:
# one hot encoding 
from sklearn.preprocessing import OneHotEncoder
if 'color_encoder' in df.keys():
    df.drop(df[['color_encoder','color_encoder1','color_encoder2']],axis=1,inplace=True)

In [9]:
df

    color
0     red
1   green
2    blue
3  orange
4   green
5    blue

In [10]:
oneHot=OneHotEncoder()
df1=oneHot.fit_transform(df[['color']])
df1.toarray()

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [11]:
# by the help of pandas 
df2=pd.get_dummies(df,columns=['color'])
df2

   color_blue  color_green  color_orange  color_red
0       False        False         False       True
1       False         True         False      False
2        True        False         False      False
3       False        False          True      False
4       False         True         False      False
5        True        False         False      False

In [12]:
# combination of handle missing value,labelencoding ,one hot encoding 
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
data1={
    'age':[10,20,np.nan,26,30],
    'gender':['male','female','others','male',None],
    'name':['dheeraj','kavi','sapu','yash','hello']
}
df1=pd.DataFrame(data1)
# handle missing value 
df1['age']=df1['age'].fillna(df1['age'].mean())
df1.dropna(inplace=True)
df1

    age  gender     name
0  10.0    male  dheeraj
1  20.0  female     kavi
2  21.5  others     sapu
3  26.0    male     yash

In [13]:
# label encoding 
le=LabelEncoder()
df1['gender1']=le.fit_transform(df1['gender'])
df1

    age  gender     name  gender1
0  10.0    male  dheeraj        1
1  20.0  female     kavi        0
2  21.5  others     sapu        2
3  26.0    male     yash        1

In [14]:
# one hot encoding 
oe=OneHotEncoder()
df2=oe.fit_transform(df1[['gender']]).toarray()
df2

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])