In [5]:
import numpy as np 
import pandas as pd 
url="https://raw.githubusercontent.com/05mohitkumar146-lgtm/DataScienceGrass/main/student-data.json"
df=pd.read_json(url)
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [21]:
# by default soting is asending
# for desencding we need to write asending=False
# delete ----> 1. Hard Delete 2.Soft Delete-+
df.sort_values('english')
# desending
df.sort_values('english',ascending=False) # not on original data 

# df.sort_values('name')

# by default ascending method 1 
df.sort_values(by=['english'],ascending=[False])

# multiple columns sorting
df.sort_values(by=['english','maths'],ascending=[False,True])
df['name']=df['name'].str.lower()
df.sort_values('name')

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

In [44]:
# add,update,delete
# add Column total = py+math+english 
df['Total']=df['english']+df['maths']+df['physics']
df
# add row 
df.loc[14]=['monu','Male',92,93,89,274]
df
# update column 

# update row

# delete column 
df.drop("Total",axis=1)
# delete row 
df.drop(14,axis=0)
df

# delete row and column

       name  gender  physics  maths  english  Total
0      arun    Male       88     87       78    253
1    rajesh    Male       96    100       95    291
2   moorthy    Male       89     90       70    249
3      raja    Male       30     25       40     95
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
6    sundar    Male       12     67       67    146
7   kavitha  Female       78     71       67    216
8    dinesh    Male       56     45       67    168
9      hema  Female       71     90       23    184
10    gowri  Female      100    100      100    300
11      ram    Male       78     55       47    180
12  murugan    Male       34     89       78    201
13  jenifer  Female       67     88       90    245
14     monu    Male       92     93       89    274

In [60]:
# Missing Values
# df.drop([6,7,8,9,10,11,12,13,14],inplace=True)
df["dateOfJoin"]=['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05','2025-06-06']
df
# string to date format 
df['dateOfJoin']=pd.to_datetime(df['dateOfJoin'])
df['dateOfJoin'].dtype

dtype('<M8[us]')

In [63]:
# date operations
df['dateOfJoin'].dt.year
df['dateOfJoin'].dt.month
df['dateOfJoin'].dt.day
df['dateOfJoin'].dt.day_name()


# 20 days 
df['dateOfJoin']+pd.to_timedelta(20,unit='D')
# 2nd way 
# df['dateOfJoin']+pd.to_timedelta("20 days")

0   2025-01-21
1   2025-02-22
2   2025-03-23
3   2025-04-24
4   2025-05-25
5   2025-06-26
Name: dateOfJoin, dtype: datetime64[us]