In [3]:
# class 16
import pandas as pd 
d={
    "Name":["vishal","virat","vineet"],# 3 rows 
    "salary":[100,200,300]
    
}
df=pd.DataFrame(data=d) 
df["Holidays"]=df["salary"]/100
df["Decrement"]=[10,20,30]
df

     Name  salary  Holidays  Decrement
0  vishal     100       1.0         10
1   virat     200       2.0         20
2  vineet     300       3.0         30

In [6]:
# delete column 
df.drop(["Decrement","Holidays"],axis=1,inplace=True)
df
# to delete from actual data we need to write inplace=True

     Name  salary
0  vishal     100
1   virat     200
2  vineet     300

In [7]:
df

     Name  salary
0  vishal     100
1   virat     200
2  vineet     300

In [8]:
# selection on rows 
df.loc[2,'Name']
df

'vineet'

In [9]:
df.iloc[2,0]

'vineet'

In [15]:
# get a single row data 
df.iloc[1]
print(df.loc[1])

Name      virat
salary      200
Name: 1, dtype: object

In [28]:
# get multiple rows 
print(df.iloc[0:3])
# get multi rows using loc 
print(df.loc[0:2])

     Name  salary
0  vishal     100
1   virat     200
2  vineet     300
     Name  salary
0  vishal     100
1   virat     200
2  vineet     300

In [24]:
# sub data get using iloc 
# in iloc the last index in slicing is excluded 
df1=df.iloc[0:2,[0]]
df1

     Name
0  vishal
1   virat

In [27]:
# sub data get using loc 
# in loc the last index is included 
df2=df.loc[0:2,["Name"]]
df2

     Name
0  vishal
1   virat
2  vineet

In [29]:
# practice ques 
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df3 = pd.DataFrame(data)

print(df3)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [43]:
print(df3['Name'])
print(df3[['Emp_ID','Salary']])
df3["Increment"]=df3["Salary"]+(df3["Salary"]*(30/100))
df3
# add rows 
df3.loc[6]=[107,'Jack','IT',60000,5,78000]
df3
# delete a single row 
df3.drop(7,inplace=True)

0    Amit
1    Riya
2     Raj
3    Sara
4    John
5    Neha
6    Jack
7    Jack
Name: Name, dtype: str
   Emp_ID  Salary
0     101   50000
1     102   45000
2     103   60000
3     104   55000
4     105   48000
5     106   52000
6     107   60000
7     107   60000

In [44]:
df3

   Emp_ID  Name Department  Salary  Experience  Increment
0     101  Amit         IT   50000           2    65000.0
1     102  Riya         HR   45000           3    58500.0
2     103   Raj    Finance   60000           5    78000.0
3     104  Sara         IT   55000           4    71500.0
4     105  John      Sales   48000           1    62400.0
5     106  Neha         HR   52000           3    67600.0
6     107  Jack         IT   60000           5    78000.0

In [ ]:
# df.drop(1)          # index label 1 delete
# df.drop([0, 2])    # multiple rows delete
# df.drop(1, inplace=True)  # permanently delete
# df.drop(df.index[1])      # position-based delete

In [48]:
# access using iloc 
df3.iloc[0]
df3.iloc[0:5]
df3.iloc[0,[1,2,3,4]]

Name           Amit
Department       IT
Salary        50000
Experience        2
Name: 0, dtype: object

In [54]:
#  access using loc 
df3.loc[0]
df3.loc[[0],["Emp_ID","Name","Department","Salary"]]
# subdata

   Emp_ID  Name Department  Salary
0     101  Amit         IT   50000

In [57]:
# update 
df3.rename(columns={"Name":"EmployeeName"},inplace=True)

In [58]:
df3

   Emp_ID EmployeeName Department  Salary  Experience  Increment
0     101         Amit         IT   50000           2    65000.0
1     102         Riya         HR   45000           3    58500.0
2     103          Raj    Finance   60000           5    78000.0
3     104         Sara         IT   55000           4    71500.0
4     105         John      Sales   48000           1    62400.0
5     106         Neha         HR   52000           3    67600.0
6     107         Jack         IT   60000           5    78000.0

In [60]:
# deletion of columns 
# single 
df3.drop("Increment",axis=1)
# multiple 
df3.drop(["Salary","Experience"],axis=1)

   Emp_ID EmployeeName Department  Salary  Experience
0     101         Amit         IT   50000           2
1     102         Riya         HR   45000           3
2     103          Raj    Finance   60000           5
3     104         Sara         IT   55000           4
4     105         John      Sales   48000           1
5     106         Neha         HR   52000           3
6     107         Jack         IT   60000           5

In [74]:
import pandas as pd 
url="https://raw.githubusercontent.com/05mohitkumar146-lgtm/DataScienceGrass/main/student-data.json"
df4=pd.read_json(url)
df4

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [77]:
# male data
male_data=df4[df4["gender"]=="Male"]
print(male_data)

df4.iloc[3:8:4]
df4.iloc[1,[3]]=96
df4

       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96     96       95
2   moorthy   Male       89     90       70
3      raja   Male       30     25       40
6    Sundar   Male       12     67       67
8    Dinesh   Male       56     45       67
11      Ram   Male       78     55       47
12  Murugan   Male       34     89       78

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96     96       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [79]:
df4["hindi"]=df4["maths"]+3
df4

       name  gender  physics  maths  english  hindi
0      arun    Male       88     87       78     90
1    rajesh    Male       96     96       95     99
2   moorthy    Male       89     90       70     93
3      raja    Male       30     25       40     28
4      usha  Female       67     45       78     48
5     priya  Female       56     46       78     49
6    Sundar    Male       12     67       67     70
7   Kavitha  Female       78     71       67     74
8    Dinesh    Male       56     45       67     48
9      Hema  Female       71     90       23     93
10    Gowri  Female      100    100      100    103
11      Ram    Male       78     55       47     58
12  Murugan    Male       34     89       78     92
13  Jenifer  Female       67     88       90     91

In [85]:
df4.loc[11:13,["name","gender","physics","maths"]]

       name  gender  physics  maths
11      Ram    Male       78     55
12  Murugan    Male       34     89
13  Jenifer  Female       67     88